rails/config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    member do
      post :sort
    end
    resources :lists, shallow: true do
      member do
        post :sort
      end
      resources :items, shallow: true do 
        collection do 
          delete :bulk_destroy
        end
      end
    end
  end

  namespace :api do
    resources :scores, only: [:index, :create]
  end

  root 'projects#index'
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  acts_as_list scope: :list

  validates_presence_of :content
end

rails/app/models/list.rb
class List < ApplicationRecord
  belongs_to :project

  has_many :items, -> { order(:position) }, dependent: :destroy

  validates_presence_of :name
end

rails/app/models/project.rb
class Project < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_many :items, through: :lists

  validates_presence_of :name
end

rails/app/controllers/api/scores_controller.rb
# Hello, curious developer. This file is here only to simulate a server's
# responses for the React exercise elsewhere in this repo. Please ignore this
# code. We know it's weird.

module Api
  class ScoresController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
      render json: [
        {
          firstName: 'The',
          lastName: 'Temp',
          score: 10
        },
        {
          firstName: 'Michael',
          lastName: 'Scott',
          score: 94
        },
        {
          firstName: 'Toby',
          lastName: 'Flenderson',
          score: 73
        },
        {
          firstName: 'Pam',
          lastName: 'Beasley',
          score: 90
        },
        {
          firstName: 'Jim',
          lastName: 'Halpert',
          score: 89
        },
        {
          firstName: 'Creed',
          lastName: 'Bratton',
          score: 56
        }
      ]
    end

    def create
      if rand(5).zero?
        render json: {
          error: 'Temporary server failure. Please try again.'
        }, status: :service_unavailable
      elsif params[:score].to_i > 100
        render json: {
          error: "#{params[:score]} is greater than 100 and is too high."
        }, status: :unprocessable_entity
      else
        render json: {
          firstName: params[:firstName],
          lastName: params[:lastName],
          score: params[:score]
        }
      end
    end
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update destroy]

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.create params[:item].permit(:content)
  end

  def edit;
    @item = Item.find(params[:id])
  end

  def update
    @item.update_attributes(params[:item].permit(:content))
  end

  def update_items
    @item.update_attributes(params[:item].permit(:content))
  end

  def destroy
    @item.destroy
  end

  # def bulk_destroy
  #   Item.where(id: params[:collection_ids]).destroy_all
  #   redirect_to root_path
  # end

  private

  def set_item
    @item = Item.where(id: params[:id]).first!
  end
end

rails/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[edit update destroy]

  def create
    @project = Project.find(params[:project_id])
    @list = @project.lists.create params[:list].permit(:name)
  end

  def edit;
    @list = List.find(params[:id])
  end

  def sort
    params[:item].each_with_index do |id, index|
      @project.items.where(id: id).update_all(position: index + 1)
    end
    head 200
  end

  def update
    @list.update_attributes(params[:list].permit(:name))
  end

  def destroy
    @list.destroy
  end

  private

  def set_list
    @list = List.where(id: params[:id]).first!
  end

end

rails/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(:name)
  end

  def sort
    params[:list].each_with_index do |id, index|
      @project.lists.where(id: id).update_all(position: index + 1)
    end
    head 200
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/views/items/_form.html.erb
<%= form_for [item], remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Save Item", name: nil, class: "btn btn-default btn-sm" %>
<% end %>

rails/app/views/items/_item.html.erb
<li class="list-group-item" id="<%= dom_id(item) %>">
  <div class="checkbox">
    <label id="checkbox">
      <input type="checkbox" name="collection_ids[]" value="<%= item.id %>"  >
      <%= item.content %>
    </label>
  </div>
  <div>
    <span class="glyphicon glyphicon-resize-vertical handle"></span>
    <%= link_to %(<span class="glyphicon glyphicon-pencil"></span>).html_safe, [:edit, item], remote: true %>
    <%= link_to %(<span class="glyphicon glyphicon-trash"></span>).html_safe, item, remote: true, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</li>

rails/app/views/items/create.js.erb
$("#<%= dom_id(@list) %> ul").append("<%=j render 'items/item', item: @item %>");
$("#<%= dom_id(@list) %>_new_item_form")[0].reset();

rails/app/views/items/destroy.js.erb
$("#<%= dom_id(@item) %>").fadeOut(300, function() { $(this).remove(); });

rails/app/views/items/edit.js.erb
$("#<%= dom_id(@item) %>").html("<%=j render 'items/form', item: @item %> ");

rails/app/views/items/update.js.erb
$("#<%= dom_id(@item) %>").html("<%=j render @item %>");

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

rails/app/views/lists/_form.html.erb
<div class="panel-header">
  <%= form_for [list],remote: true,  html: { class: "form-inline" } do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Update List Name", name: nil, class: "btn btn-default btn-sm" %>
  <% end %>
</div>

rails/app/views/lists/_list.html.erb
<article class="panel panel-default" id="<%= dom_id(list) %>">

  <div class="panel-heading">
  <h3><%= list.name %></h3>
    <%= link_to %(<span class="glyphicon glyphicon-pencil"></span>).html_safe, [:edit, list], remote: true %>
    <%= link_to %(<span class="glyphicon glyphicon-trash"></span>).html_safe, list, remote: true, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

    <ul class="list-group sortable" data-update-url="<%= sort_list_path(list) %>">
      <%= render list.items %>
    </ul>
    <div class="panel-footer">
    </div>

  <div class="panel-footer">
    <%= form_for [list, Item.new], remote: true, html: { class: "form-inline", id: "#{dom_id(list)}_new_item_form" } do |f| %>
      <div class="form-group">
        <%= f.text_field :content, class: "form-control" %>
      </div>
      <%= f.submit "Add Item", name: nil, class: "btn btn-default btn" %>
    <% end %>
  </div>

</article>

rails/app/views/lists/create.js.erb
$("#project_lists").append("<%=j render 'lists/list', list: @list %>");
$("#form" )[0].reset();

rails/app/views/lists/destroy.js.erb
$("#<%= dom_id(@list) %>").fadeOut(300, function() { $(this).remove(); });

rails/app/views/lists/edit.js.erb
$("#<%= dom_id(@list) %>").html("<%=j render 'lists/form', list: @list %> ");

rails/app/views/lists/update.js.erb
$("#<%= dom_id(@list) %>").html("<%=j render @list %>");

rails/app/views/projects/_project.html.erb
<article id="<%= dom_id(project) %>">

  <h2 class="heading"> Project Name: <%= project.name %></h2>

  <ul >
    <%= form_for [project, List.new], remote: true, html: { class: "form-inline", id: "form" } do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control" %>
      </div>
        <%= f.submit "Add List", name: nil, class: "btn btn-primary btn" %>
      <% end %>
    </ul>

    <ul id="project_lists" class="project-group sorul" data-update-url="<%= sort_project_path(project) %>">
        <%= render project.lists %>
    </ul>

</article>

rails/app/views/projects/index.html.erb
<main class="container">
  <div class="row">
  <div class="col-md-3 "> </div>
    <section class="col-md-6">
      <h1 class="heading">Super ToDo!</h1>
      <h5 class="heading"> Organize Your Life </h5>
        <%= render @projects %>
    </section>
    <div class="col-md-3"> </div>
  </div>
</main>

<script type="text/javascript">
  $(function() {
    return $(".sortable").sortable({
      axis: "y",
      handle: ".handle",
      update: function() {
        return $.post($(this).data("update-url"), $(this).sortable("serialize"));
      }
    });
  });
</script>